const botConfig = require("../botconfig.json");
const Discord = require("discord.js");
const fs = require('fs');
const path = require('path');

module.exports.run = async (bot, msg, args) => {
    if(!args[0] || !args[1]) return msg.channel.send(`Are you sure you typed in the command correctly? To generate a meme, use \`${botConfig.prefix}meme <facts/drake> <caption>\`.`);
    strArray = args.slice(1);
    str = strArray.join(" ");
    if(args[0] === "facts") {
        strDiv = str.match(/.{1,16}/g);
        const Canvas = require('canvas')
        , Image = Canvas.Image
        , canvas = new Canvas(378, 498)
        , ctx = canvas.getContext('2d');
        fs.readFile('images/factsoriginal.png', function(err, meme){
            if (err) throw err;
            img = new Image;
            img.src = meme;
            ctx.drawImage(img, 0, 0, img.width, img.height);
            ctx.font = '15px Arial';
            ctx.rotate(.17);
            ctx.fillText(strDiv[0], 80, 328);
            if(strDiv[1]) ctx.fillText(strDiv[1], 80, 348);
            if(strDiv[2]) ctx.fillText(strDiv[2], 80, 368);
            if(strDiv[3]) ctx.fillText(strDiv[3], 80, 388);
            if(strDiv[4]) ctx.fillText(strDiv[4], 80, 408);
            if(strDiv[5]) ctx.fillText(strDiv[5], 80, 428);
            canvas.createPNGStream().pipe(fs.createWriteStream(path.join('images/facts.png')));
        });
        return setTimeout(function(){
            msg.channel.send(`*Generated by ${msg.author.username}*`, {files: ["./images/facts.png"]});
        }, 2000);
    } else if(args[0] === "drake") {
        strA = str.split("|")
        const Canvas = require('canvas')
        , Image = Canvas.Image
        , canvas = new Canvas(640, 550)
        , ctx = canvas.getContext('2d');
        fs.readFile('images/drakeoriginal.png', function(err, meme){
            if (err) throw err;
            img = new Image;
            img.src = meme;
            ctx.drawImage(img, 0, 0, img.width, img.height);
            ctx.font = '36px Arial';
            ctx.fillText(strA[0], 373, 114);
            if(strA[1]) ctx.fillText(strA[1], 373, 388);
            canvas.createPNGStream().pipe(fs.createWriteStream(path.join('images/drake.png')));
        });
        return setTimeout(function(){
            msg.channel.send(`*Generated by ${msg.author.username}*`, {files: ["./images/drake.png"]});
        }, 2000);
    }
    msg.channel.send(`Are you sure you typed in the command correctly? To generate a meme, use \`${botConfig.prefix}meme <facts/drake> <caption>\`.`);
}

module.exports.help = {
    name: "meme"
}